server:
  domain: "eventbubble.lennadi.com"
  error:
    include-stacktrace: never
    include-exception: false
    include-message: always
spring:
  profiles:
    active: keinCaptcha, EMAIL_dummy
  application:
    name: "eventbubble30"
app:
  jwt:
    secret: ${JWT_SECRET:DEVSECRET_NICHT_IN_PROD_BITTE_123}
    access-token-validity-ms: 900000 #15m
    refresh-token-validity-ms: 2592000000 #30d