logging:
  level:
    org.springframework.security: info
server:
  domain: ${DOMAIN:localhost:8000}
  error:
    include-stacktrace: never
    include-exception: false
    include-message: never
    whitelabel:
      enabled: false
spring:
  profiles:
    active: keinCaptcha, EMAIL_dummy, memoryStorage
  application:
    name: "eventbubble30"
  main:
    web-application-type: servlet
app:
  jwt:
    secret: ${JWT_SECRET:dev-secret-no-good-how-do-i-prevent-accidentally-using-this}
    access-token-validity-ms: 900000 #15m
    refresh-token-validity-ms: 2592000000 #30d
cleanup:
  BenutzerEmailVer-d: 7