logging:
  level:
    org.springframework.security: info
server:
  domain: ${DOMAIN}
  error:
    include-stacktrace: never
    include-exception: false
    include-message: always
    whitelabel:
      enabled=true:
spring:
  profiles:
    active: keinCaptcha, EMAIL_dummy, memoryStorage
  application:
    name: "eventbubble30"
app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-validity-ms: 900000 #15m
    refresh-token-validity-ms: 2592000000 #30d
cleanup:
  BenutzerEmailVer-d: 7