server:
  error:
    include-stacktrace: never
    include-exception: false
    include-message: always
  servlet:
    session:
      timeout: 30m # das wird noch Kacke. Vlt doch lieber Tokens....
spring:
  profiles:
    active: keinCaptcha
  application:
    name: "eventbubble30"