name: Bauch-Beine-Po
run-name: ${{github.actor}} hat Änderungen gepusht.
on:
  push:
    branches: ["master"]
jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout und Aufstehen. Zehennägel schneiden.
      uses: actions/checkout@v3

    - name: JDK 17 aufsetzen und Hose anziehen.
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: JAR bauen und mit Parfüm einsprühen.
      run: |
        chmod +x gradlew
        ./gradlew build -x test
        ls build/libs

    - name: JAR hochladen und rausgehen.
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "build/libs/*.jar"
        target: "/home/${{ secrets.SSH_USER }}/eventbubble/"
        strip_components: 2
        overwrite: true

    - name: Backend neustarten und Hunde in der Straßenbahn mit Schokolade füttern.
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /home/${{ secrets.SSH_USER }}/eventbubble
          JAR=$(ls *.jar)
          mv "$JAR" app.jar
          cd ..
          docker compose down
          docker compose build --no-cache
          docker compose up -d
          chafa --animate=once larry-larry-baby.gif
